//
//  DashboardInteractor.swift
//  Movie Trailer App
//
//  Created Alonso Fabian Orozco Perez on 28/12/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by ___ORGANIZATIONNAME___
//

import Foundation
enum MoviesType {
    case popular
    case topRated
}

//MARK: Interactor protocol -
protocol DashboardInteractorProtocol: class {
    var queue: OperationQueue? { get set }
    func loadMoviesData(ofType type: MoviesType, withPage numberPage: Int, completion: @escaping ([MovieRecord], Error?) -> Void)
}

//MARK: Interactor implementation -
class DashboardInteractor: DashboardInteractorProtocol {
    
    weak var queue: OperationQueue?
    
    func loadMoviesData(ofType type: MoviesType, withPage numberPage: Int, completion: @escaping ([MovieRecord], Error?) -> Void) {
        let movieDataOperation = MovieDataDownloader(forMovieType: type)
        movieDataOperation.completionBlock = {
            completion(movieDataOperation.movies, movieDataOperation.error)
        }
        queue?.addOperation(movieDataOperation)
    }
    
}
