//
//  LoginPresenter.swift
//  Movie Trailer App
//
//  Created Alonso Fabian Orozco Perez on 28/12/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by ___ORGANIZATIONNAME___
//

import Foundation

// MARK: View -
protocol LoginViewProtocol: class {
    func showProgress()
    func hideProgress()
    func onSucessLogin()
    func onRequestFailed(error: String)
}

// MARK: Presenter -
protocol LoginPresenterProtocol: class {
    var view: LoginViewProtocol? { get set }
    func viewDidLoad()
    func performLogin(username: String, password: String)
}

class LoginPresenter: LoginPresenterProtocol {
    
    weak var view: LoginViewProtocol?
    
    private var interactor: LoginInteractorProtocol?

    func viewDidLoad() {
        interactor = LoginInteractor()
    }
    
    func performLogin(username: String, password: String) {
        view?.showProgress()
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            self.interactor?.requestLogin(username: username, password: password, completion: { (success, error) in
                self.view?.hideProgress()
                if success {
                    self.view?.onSucessLogin()
                }else {
                    if let serverError = error {
                        self.view?.onRequestFailed(error: serverError.localizedDescription)
                    }else {
                        self.view?.onRequestFailed(error: "An error has ocurred, try later")
                    }
                }
            })
        }
    }
}
