//
//  MoviesFooterInteractor.swift
//  Movie Trailer App
//
//  Created Alonso Fabian Orozco Perez on 29/12/20.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by ___ORGANIZATIONNAME___
//

import Foundation

//MARK: Interactor protocol -
protocol MoviesTopInteractorProtocol: class {
    func loadUpcommingMovies(completion: @escaping ([MovieListResultObject], MTServiceError?) -> Void)
}

//MARK: Interactor implementation -
class MoviesFooterInteractor: MoviesTopInteractorProtocol {
    
    func loadUpcommingMovies(completion: @escaping ([MovieListResultObject], MTServiceError?) -> Void) {
        MTService.genericRequest(router: .upcomingMovies) { (result: MTServiceResult<MoviesResponse>) in
            
            switch result {
            
            case .success(let response):
                completion(response.results, nil)
                
            case .failure(let error):
                completion([], error)
            }
        }
    }
   
    
}
